### ISSUE TITLE
Certificate problem during pairing process

### ISSUE THREAD

**Issue by hal9079** [holomekc/ioBroker.bshb#8]
I've got always the same SSL error on  an ioBroker installation: Raspbian Buster, node v10.18.0 and npm v 6.13.4. Even with the standard image from ioBroker I got the same error:

```
host.raspberrypi	2019-12-30 22:43:05.703	info	Restart adapter system.adapter.bshb.0 because enabled
host.raspberrypi	2019-12-30 22:43:05.702	info	instance system.adapter.bshb.0 terminated with code 0 (NO_ERROR)
host.raspberrypi	2019-12-30 22:43:05.701	error	Caught by controller[0]: at WriteWrap.afterWrite [as oncomplete] (net.js:789:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }
host.raspberrypi	2019-12-30 22:43:05.699	error	Caught by controller[0]: { Error: write EPROTO 3070073296:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert
bshb.0	2019-12-30 22:43:05.147	info	(1298) Terminated (NO_ERROR): Without reason
bshb.0	2019-12-30 22:43:05.144	info	(1298) terminating
bshb.0	2019-12-30 22:43:05.130	info	(1298) cleaned everything up...
bshb.0	2019-12-30 22:43:05.125	error	at WriteWrap.afterWrite [as oncomplete] (net.js:789:14)
bshb.0	2019-12-30 22:43:05.125	error	(1298) Error: write EPROTO 3070073296:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 46
bshb.0	2019-12-30 22:43:05.124	error	(1298) uncaught exception: write EPROTO 3070073296:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number
bshb.0	2019-12-30 22:43:04.539	info	(1298) Start detecting devices. This may take a while.
bshb.0	2019-12-30 22:43:04.537	info	(1298) Unexpected pairing response. Most likely wrong input data. Check password, etc. Pairing stopped.
bshb.0	2019-12-30 22:43:03.391	info	(1298) Start pairing. Activate pairing on Bosch Smart Home Controller by pressing button until flashing.
bshb.0	2019-12-30 22:43:03.391	info	(1298) Client with identifier: ioBroker.bshb_f1d53550-0484-4eab-b0be-3e6871efb0c3 was not paired yet.
bshb.0	2019-12-30 22:43:02.683	info	(1298) Check if client with identifier: ioBroker.bshb_f1d53550-0484-4eab-b0be-3e6871efb0c3 is already paired.
bshb.0	2019-12-30 22:43:02.678	info	(1298) Client certificate stored in system.certificates.
bshb.0	2019-12-30 22:43:00.624	info	(1298) No client certificate found in old configuration or it failed. Generate new certificate
bshb.0	2019-12-30 22:43:00.623	error	(1298) Could not find client certificate for identifier: ioBroker.bshb_f1d53550-0484-4eab-b0be-3e6871efb0c3.
bshb.0	2019-12-30 22:43:00.621	info	(1298) Found old configuration in certsPath: /home/iobroker/certs. Try to read information
bshb.0	2019-12-30 22:43:00.619	info	(1298) Could not find client certificate. Check for old configuration
bshb.0	2019-12-30 22:43:00.509	info	(1298) starting. Version 0.1.0 in /opt/iobroker/node_modules/iobroker.bshb, node: v10.17.0
host.raspberrypi	2019-12-30 22:42:58.543	info	instance system.adapter.bshb.0 started with pid 1298
host.raspberrypi	2019-12-30 22:42:58.518	info	"system.adapter.bshb.0" enabled
```

**Comment by holomekc** [comment]
Hi. 
From the following log you can see that the adapter got an response from the controller:
Unexpected pairing response. Most likely wrong input data. Check password, etc. Pairing stopped.

Could you please first check this (Check wiki on github)? When you are sure that your configuration is correct you can also set the log level to „silly“ which then contains detail HTTP request information. But please make sure that you do not post sensitive data here e.g. Your password. You can always send me the log information via email in case you are not sure if you removed all sensitive info.

Regarding the error in more detail. The controller rejected the pairing request which then results in the issue that the adapter is not paired. After that the detection of devices is failing because the controller does not accept the client certificate. 
The normal behavior is: 
1. Adapter checks if it is paired. Which is not the case
2. adapter tries to send pairing request
3. request rejected by contoller because controller is not in pairing mode. You see a log information asking you to enable pairing mode. This only happens when an ssl handshake error occurs here
4. adapter receives a valid HTTP response with 201 which indicates that adapter is paired correctly. In your case the code was not 201.

**Comment by hal9079** [comment]
Send the requested logs via mail. Thanks!

**Comment by holomekc** [comment]
It was a configuration issue. Issue closed.
